typography_spectrum: 0.2200708466116339
color:
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  brandStrength: 0.7240297296084464
  lightness: 0.31315979547798634
  saturation: 0.40418616333045065
  rhythmicContrast: 0.3578927624039352
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.005670058540999889
analytics:
  google: UA-50466530-5
  facebook: null
  twitter: null
name: Jason Loong
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Instagram qwebie
    url: 'https://www.instagram.com/qwebie/'
    type: external
  - name: B&W on myportfolio.com
    url: 'https://jasonloong.myportfolio.com/'
    type: external
favicon: null
title: the Grid of Jason Loong
description: still testing the grid
purpose: []
