name: Jason Loong
favicon: null
layout_spectrum: 0.8569931061938405
typography_spectrum: 0.6913788765668869
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.747698113322258
  lightness: 0.8403654401190579
  saturation: 0.15332186524756253
  rhythmicContrast: 0.8563858685083687
purpose: []
