name: Jason Loong
favicon: null
layout_spectrum: 0.50456
typography_spectrum: 0.24865
title: the Grid of Jason Loong
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-50466530-5
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#686f75'
    - '#3b434a'
    - '#e1e2e4'
    - '#babec1'
  brandStrength: 0.25
  lightness: 0.25
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
